bind 0.0.0.0
port 7003
protected-mode no
appendonly no
cluster-enabled yes
cluster-config-file nodes-7003.conf
cluster-node-timeout 5000
cluster-preferred-endpoint-type ip
cluster-announce-ip 172.28.0.13
cluster-announce-port 7003
