bind 0.0.0.0
port 7006
protected-mode no
appendonly no
cluster-enabled yes
cluster-config-file nodes-7006.conf
cluster-node-timeout 5000
cluster-preferred-endpoint-type ip
cluster-announce-ip 172.28.0.16
cluster-announce-port 7006
